version: "3"
services:
  frontend:
    build:
      context: "./frontend"
      args:
        - VERSION=development
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    command: npm start
  backend:
    build:
      context: "./backend"
      args: 
        PORT: 4000
    volumes:
      - ./backend:/backend
    command: /bin/sh -c "rm -f /backend/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "4000:3000"
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./db/mysql-confd:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'