version: "2"
services:
  frontend:
    image: opendoor222/frontend
    mem_limit: 268435456
    build:
      context: "./frontend"
      args:
        - VERSION=development
    ports: 
      - "80:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    command: npm start
  backend:
    image: opendoor222/backend
    mem_limit: 268435456
    build:
      context: "./backend"
      args: 
        PORT: 4000
    volumes:
      - ./backend:/backend
    command: /bin/sh -c "rm -f /backend/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "4000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: opendoor222/db
    mem_limit: 268435456
    build:
      context: "./db"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '4306:3306'