version: "2"
services:
  frontend:
    image: opendoor222/frontend
    mem_limit: 268435456
    build:
      args:
        - VERSION=development
    ports: 
      - "3000:3000"
    command: npm start
  backend:
    image: opendoor222/backend
    mem_limit: 268435456
    build:
      args: 
        PORT: 4000
    command: /bin/sh -c "rm -f /backend/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "4000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: opendoor222/mysql:8.0
    mem_limit: 268435456
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./db/mysql-confd:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '4306:3306'